# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notisiario',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('pubdate', models.DateField()),
                ('category', models.CharField(max_length=15)),
                ('title', models.TextField()),
                ('language', models.CharField(max_length=3)),
                ('content', models.TextField()),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=10)),
            ],
        ),
    ]
